parameters:
  artifact: false

jobs:
- job: Framework
  workspace:
    clean: all
  variables:
  - template: ../variables.yml
  steps:
  - template: steps/build.yml
    parameters:
      path: ${{ variables.frameworkPath }}
      lint: true
      test: true
      pack: true
      outputPath: ${{ variables.frameworkArtifactPath }}
  - ${{ if eq(parameters.artifact, true) }}:
    - template: steps/publish.yml
      parameters:
        name: ${{ variables.frameworkArtifactName }}
        path: ${{ variables.frameworkArtifactPath }}
