parameters:
  environmentName: ""

jobs:
- deployment: Extension
  environment: ${{ parameters.environmentName }}
  workspace:
    clean: all
  variables:
  - template: ../variables.yml
  strategy:
    runOnce:
      deploy:
        steps:
        - download: none
        - template: steps/artifact-download.yml
          parameters:
            name: ${{ variables.extensionArtifactName }}
            path: ${{ variables.extensionArtifactPath }}
        - template: steps/publish-extension.yml
          parameters:
            path: ${{ variables.extensionArtifactPath }}
            endpointName: ${{ variables.marketplaceEndpoint }}
