parameters:
  environmentName: ""
  dryRun: false

jobs:
- deployment: Framework
  environment: ${{ parameters.environmentName }}
  workspace:
    clean: all
  variables:
  - template: ../variables.yml
  strategy:
    runOnce:
      deploy:
        steps:
        - template: steps/artifact-download.yml
          parameters:
            name: ${{ variables.frameworkArtifactName }}
            path: ${{ variables.frameworkArtifactPath }}
        - template: steps/artifact-extract.yml
          parameters:
            path: ${{ variables.frameworkArtifactPath }}/*.tgz
            outputPath: ${{ variables.frameworkArtifactPath }}
        - template: steps/publish-node.yml
          parameters:
            endpointName: ${{ variables.npmjsEdpoint }}
            path: ${{ variables.frameworkArtifactPath }}/package
            dryRun: ${{ parameters.dryRun }}
