trigger: none

queue:
  name: Hosted VS2017

steps:
- task: Npm@1
  displayName: Restore packages
  inputs:
    command: install

- task: Npm@1
  displayName: Run build
  inputs:
    command: custom
    customCommand: run build

- task: Npm@1
  displayName: Run tests
  inputs:
    command: custom
    customCommand: run test

- task: PublishTestResults@2
  displayName: Publish test results
  inputs:
    testResultsFiles: test-*.xml
  condition: always()