trigger: none

pr:
  branches:
    include:
    - main
  paths:
    include:
    - src/*
  autoCancel: true

pool:
  name: Default

jobs:
- template: templates/build-framework.yml
  parameters:
    artifact: true
- template: templates/build-task.yml
  parameters:
    artifact: true
- template: templates/build-extension.yml
  parameters:
    artifact: true
