trigger: none

pr:
  branches:
    include:
    - master
  paths:
    include:
    - src/*
  autoCancel: true

pool:
  name: Default

variables:
- template: templates/variables.yml

jobs:
- job: Framework
  workspace:
    clean: all
  steps:
  - template: templates/build.yml
    parameters:
      path: ${{ variables.frameworkPath }}
      restore: true
      lint: true
      build: true
      test: true
      pack: true
      outputPath: ${{ variables.frameworkArtifactPath }}
  - template: templates/publish.yml
    parameters:
      name: ${{ variables.frameworkArtifactName }}
      path: ${{ variables.frameworkArtifactPath }}

- job: Task
  workspace:
    clean: all
  dependsOn:
  - Framework
  steps:
  - template: templates/download.yml
    parameters:
      name: ${{ variables.frameworkArtifactName }}
      path: ${{ variables.frameworkPath }}
  - template: templates/build.yml
    parameters:
      path: ${{ variables.taskPath }}
      restore: true
      lint: true
      build: true
