trigger: none

pool:
  vmImage: windows-latest

steps:
- task: Npm@1
  displayName: Restore packages
  inputs:
    command: install

- task: Npm@1
  displayName: Run lint
  inputs:
    command: custom
    customCommand: run lint

- task: Npm@1
  displayName: Run build
  inputs:
    command: custom
    customCommand: run build

- task: Npm@1
  displayName: Run tests
  inputs:
    command: custom
    customCommand: run test

- task: PublishTestResults@2
  displayName: Publish test results
  inputs:
    testResultsFiles: test-*.xml
  condition: always()
