trigger:
  branches:
    include:
    - master
  paths:
    exclude:
    - src/task

pr: none

pool:
  name: Default

stages:
- stage: Build
  jobs:
  - template: templates/build-framework.yml
    parameters:
      artifact: true
  - template: templates/build-task.yml
    parameters:
      artifact: true

- stage: Release
  dependsOn:
  - Build
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  jobs:
  - template: templates/release-framework.yml
    parameters:
      dryRun: true
