trigger:
  branches:
    include:
    - master
  paths:
    exclude:
    - src/task

pr: none

pool:
  name: Default

stages:
- stage: Build
  jobs:
  - template: templates/build-framework.yml
    parameters:
      artifact: true
  - template: templates/build-task.yml
    parameters:
      artifact: true
  - template: templates/build-extension.yml
    parameters:
      artifact: true

- stage: Preview
  dependsOn:
  - Build
  jobs:
  - template: templates/preview.yml
    parameters:
      environmentName: Marketplace

- stage: Release
  dependsOn:
  - Build
  jobs:
  - template: templates/release-framework.yml
    parameters:
      environmentName: NpmJs
      dryRun: ${{ ne(variables['Build.SourceBranch'], 'refs/heads/master') }}
