trigger:
  branches:
    include:
    - master
  paths:
    exclude:
    - src/task

pr: none

pool:
  name: Default

jobs:
- template: templates/build-framework.yml
  parameters:
    artifact: true

- template: templates/build-task.yml
  parameters:
    artifact: true
