trigger:
  branches:
    include:
    - main
  paths:
    exclude:
    - src/task

pr: none

pool:
  name: Default

parameters:
- name: releaseFramework
  displayName: Release framework
  type: boolean
  default: true

stages:
- stage: Build
  jobs:
  - template: templates/build-framework.yml
    parameters:
      artifact: true
  - template: templates/build-task.yml
    parameters:
      artifact: true
  - template: templates/build-extension.yml
    parameters:
      artifact: true

- stage: Preview
  dependsOn:
  - Build
  jobs:
  - template: templates/release-extension.yml
    parameters:
      environmentName: Marketplace
      preview: true

- stage: Release
  dependsOn:
  - Build
  - Preview
  jobs:
  - template: templates/release-extension.yml
    parameters:
      environmentName: Marketplace
  - ${{ if eq(parameters.releaseFramework, true) }}:
    - template: templates/release-framework.yml
      parameters:
        environmentName: NpmJs
        dryRun: ${{ ne(variables['Build.SourceBranch'], 'refs/heads/main') }}
